// <auto-generated />
using System;
using LearnNetCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LearnNetCore.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200910045158_Employee")]
    partial class Employee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LearnNetCore.Models.Departments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreateDate");

                    b.Property<DateTimeOffset>("DeleteDate");

                    b.Property<string>("Name");

                    b.Property<bool>("isDelete");

                    b.Property<DateTimeOffset>("updateDate");

                    b.HasKey("Id");

                    b.ToTable("tb_m_departments");
                });

            modelBuilder.Entity("LearnNetCore.Models.Divisions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreateDate");

                    b.Property<DateTimeOffset>("DeleteDate");

                    b.Property<string>("Name");

                    b.Property<int>("department_id");

                    b.Property<bool>("isDelete");

                    b.Property<DateTimeOffset>("updateDate");

                    b.HasKey("Id");

                    b.HasIndex("department_id");

                    b.ToTable("tb_m_divisions");
                });

            modelBuilder.Entity("LearnNetCore.Models.Employees", b =>
                {
                    b.Property<string>("EmpId");

                    b.Property<string>("Adress");

                    b.Property<DateTimeOffset>("CreateTime");

                    b.Property<DateTimeOffset>("DeleteTime");

                    b.Property<bool>("IsDelete");

                    b.Property<DateTimeOffset>("UpdateTime");

                    b.HasKey("EmpId");

                    b.ToTable("tb_m_mployee");
                });

            modelBuilder.Entity("LearnNetCore.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.ToTable("tb_m_Role");
                });

            modelBuilder.Entity("LearnNetCore.Models.RoleUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("tb_m_RoleUser");
                });

            modelBuilder.Entity("LearnNetCore.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("tb_m_user");
                });

            modelBuilder.Entity("LearnNetCore.Models.Divisions", b =>
                {
                    b.HasOne("LearnNetCore.Models.Departments", "Departments")
                        .WithMany()
                        .HasForeignKey("department_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LearnNetCore.Models.Employees", b =>
                {
                    b.HasOne("LearnNetCore.Models.User", "User")
                        .WithOne("Employees")
                        .HasForeignKey("LearnNetCore.Models.Employees", "EmpId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LearnNetCore.Models.RoleUser", b =>
                {
                    b.HasOne("LearnNetCore.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("LearnNetCore.Models.User", "User")
                        .WithMany("userRoles")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
